# This file contains values from Cookiecutter

default_context:
  project_name: "datawrapper"
  project_description: "A light-weight python wrapper for the Datawrapper API (v3). While it is not developed by Datawrapper officially, you can use it with your API credentials from datawrapper.de"
  organization: "chekos"
  license: "MIT"
  version: "0.4.5"
  github_name: "chekos"
  email: "chekos@tacosdedatos.com"
